#! /bin/bash
# Xzinud-skel
# Version 0.1
#
## +------------------------------------------------------------+
# | mermouy@gmail.com
# |
# | This program is free software; you can redistribute it and/or
# | modify it under the terms of the GNU General Public License
# | as published by the Free Software Foundation; either version
# | 3 of the License, or (at your option) any later version.
# | 
# | This program is distributed in the hope that it will be useful,
# | but WITHOUT ANY WARRANTY; without even the implied warranty
# | of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# | See the GNU General Public License for more details.
# |
# | You should have received a copy of the GNU General Public
# | License along with this program; if not, write to the
# | Free Software Foundation, Inc., 51 Franklin St,
# | Fifth Floor, Boston, MA  02110-1301  USA
# +------------------------------------------------------------+
#
		### VARIABLES ###

# Icône des fenêtres
Zinicon="/usr/share/pixmaps/zinud/horned-logo.png"

# Dossier contenant les fichiers de langues
Zinlangrep="/usr/share/zinud/lang"

		### LANGUE ###

#Liste des fichiers de langues disponibles listé pour zenity-list
LIST=`ls -m $Zinlangrep | sed -e 's/.cfg,/ FALSE/g' |  sed -e 's/.cfg//g' | sed -e 's/^/FALSE /' | sed -e 's/FALSE en/TRUE en/g'`

#Vérification langue choisie sinon la choisir, ou utiliser en par défaut

while [ ! -f ~/.config/zinud/lang.cfg ]
do
	. $Zinlangrep/en.cfg
	zenity --question --window-icon="$Zinicon" --title="$Zininstall" --text="$Zininstalltxt" || exit 0
	if [ $? = "0" ]
	then
	Chlang=$(zenity --list \
		--radiolist \
		--window-icon="$Zinicon" \
		--title="$Language" \
		--window-icon="$Zinicon" \
		--text="$Langconf" \
		--print-column="2" \
		--column "$Select" \
		--column "$Availang" \
		$LIST) || exit 0
		cp -vf $Zinlangrep/$Chlang.cfg ~/.config/zinud/lang.cfg
		. ~/.config/zinud/lang.cfg
	else
	cp -vf $Zinlangrep/en.cfg ~/.config/zinud/lang.cfg
	. ~/.config/zinud/lang.cfg
	zenity --window-icon="$Zinicon" --info --text="$Engdef"
	fi
done

#on source ce fichier de langue 
. ~/.config/zinud/lang.cfg

		### /LANGUE ###

# Vérification de l'entrée utilisateur
username=$( ls -1 /home | grep -v lost+found | zenity --title="ZinuD-SkeL User" --window-icon="$Zinicon" --list --column="$Usertxt" --text="$Selectuserupdt" || echo "cancel" )

# Dossiers à traiter
dub="/home/$username/.config"
dua="$dub/zinud"
duc="$dub/compiz"
zinrep="/usr/share/zinud"
tempdiag="/tmp/tmpdiag"
dud="/home/$username"


		### /VARIABLES ###

		### FONCTIONS ###

function Addgroups () {
gruplist="plugdev haldaemon users powerdev disk cdrom audio dialout dip fuse games lp lpadmin video disk sudo"
for i in $gruplist
do
	adduser $username $i
done
echo "Done, you can close this window..."
}

function Zinudskel (){
#Création des dossiers de config
	mkdir -vp $dua
	mkdir -vp $dub/Thunar
	mkdir -vp $dub/cairo-dock
	mkdir -vp $duc
#Copie des fichier de config utilisateur
	cd $zinrep/zinud/
	cp -vf *.sh $dua/
	chmod +x $dua/*.sh
	cp -vf zinudfirstboot $dua/.zinudfirstboot
	if [ -f $dub/Thunar/uca.xml ]
		then mv $dub/Thunar/uca.xml $dub/Thunar/uca.xml~
	fi
	cp -vf uca.xml $dub/Thunar/	
	cp -vf thunarrc $dub/Thunar/
	if [ -f $dud/.bashrc ]
		then mv $dud/.bashrc $dud/.bashrc~
		cp -vf bashrc $dud/.bashrc
	fi
	if [ -f $dud/.bash_aliases ]
		then mv -v $dud/.bash_aliases $dud/.bash_aliases~
	fi
	cp -vf bash_aliases $dud/.bash_aliases
	if [ -f $dud/.gtkrc-2.0 ]
		then mv -v $dud/.gtkrc-2.0 $dud/.gtkrc-2.0~
	fi
	cp -vf gtkrc-2.0 $dud/.gtkrc-2.0
	if [ -d $dub/roxterm.sourceforge.net ]
		then mv -v $dub/roxterm.sourceforge.net $dub/roxterm.sourceforge.net.old
	fi
	cd ..
	cp -rvf roxterm.sourceforge.net $dub/
	if [ -e /usr/bin/nitrogen ]
		then cp -rvf nitrogen $dub/
	fi
	cd $dub/cairo-dock/
	mv -vf current_theme current_theme.old
	wget zinud.youm.org/zinud.theme.tar.bz2
	tar -xjf zinud.theme.tar.bz2
	mv -v zinud.theme current_theme
	chmod -R 755 $dub/
	cd $duc/
	cp -rvf $zinrep/compizconfig/ .
	chown -R $zuser:$zuser $dud
}

		### /FONCTONS ###

		### SCRIPT ###

if [ "$username" = "cancel" ]
then 
	exit 0
else 
	zenity --title="ZinuD-SkeL User" --window-icon="$Zinicon" --question --text="$Updatesur <b>$username</b>?"
	if [ "$?" = "0" ]
	then
# Configuration Squelette Utilisateur
		Zinudskel | zenity --window-icon="$Zinicon" --title="ZinuD-SkeL" --text-info --height=600 --width=700
	fi
fi

#Ajout de l'utilisateur au groupes systemes
Addgroups | zenity --window-icon="$Zinicon" --title="ZinuD-SkeL Groups" --text-info --height=600 --width=500

# Choix du mode de connexion
zenity --window-icon="$Zinicon" --title="ZinuD-SkeL Login" --question --text="$Userlogin"
if [ $? = "0" ]
then
	exec /usr/local/sbin/xlogin-configurator
else
	zenity --window-icon="$Zinicon" --title="ZinuD-SkeL" --text="$Userupdted" --info
fi

